steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/BarBichachi/DevOpsFinal.git', '.']
  id: Clone Repository

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['storage', 'cp', './index.jsp', 'gs://devops-final-project-bucket/index.jsp']
  id: Upload JSP to Cloud Storage

options:
  logging: CLOUD_LOGGING_ONLY
